apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: example-hotrod
  ports:
    - name: tracing
      protocol: UDP
      port: 6831
      targetPort: tracing-jaeger
    - name: frontend
      protocol: TCP
      port: 16686
      targetPort: frontend-jaeger
